### ISSUE TITLE
Compillation error

### ISSUE THREAD

**Issue by darkslategrey** [oltarasenko/crawly_ui#60] opened 2020-12-25 23:16 UTC
Hi, 

I try to compile locally the latest master :
```
commit 3b95de73299c4f62b84fa6f41418e2ffd0885dca (HEAD -> master, origin/master, origin/HEAD)
Author: Oleg Tarasenko <oltarasenko@gmail.com>
Date:   Mon Dec 21 12:02:09 2020 +0100

    Speedup logs
```

```
$ iex -S mix phx.server`

`== Compilation error in file lib/crawly_ui_web/views/job_view.ex ==
** (SyntaxError) lib/crawly_ui_web/templates/job/spider.html.leex:26: unexpected token: end
```

My local env : 
```
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 20)
```

**Comment by oltarasenko** [comment] 2020-12-26 08:23
Hey @darkslategrey I am away from computer. Will have a look later tonight

**Comment by oltarasenko** [comment] 2020-12-26 20:57
It seems to be specific to your environment. I will try to install the same versions as you have to verify the problem, however in general, due to the fact that I have a very limited amount of time, I don't plan to support old versions of OTP/Elixir

**Comment by oltarasenko** [comment] 2020-12-28 07:59
@darkslategrey I am having problems reproducing the issue. Could you explain which version of Erlang(as I see it's 22)/Elixir(as I see it's 1.9 compiled on OTP 20?) was used, what operating system you're using?

**Comment by oltarasenko** [comment] 2020-12-29 07:13
I will close it for now, as I can't reproduce the case on my env and need more information. Please feel free to reopen it once you will get more data.

**Closed by oltarasenko** 2020-12-29 07:13 UTC
